<style>div.comment {color:blue}</style>
---
title: "Scene Bias"
output: html_document
---
```{r set-up, warning=FALSE, message=FALSE, results="hide"}
# Clear workspace
rm(list = ls())

# Load helper functions
source('helper_functions.R')

# Import libraries
packages = c("tidyr","dplyr","ggplot2","lme4","lmerTest","Hmisc","car","lmtest","Rarity","cowplot")
ipak(packages)

# Redo long calculations
redo_calc = 0;

```

```{r load-data}
# Read data
AllData = read.csv("../data/AllData.csv")

# Convert to factors
AllData$Sub = as.factor(AllData$Sub)
AllData$Pred = as.factor(AllData$Pred)
AllData$Want2See = as.factor(AllData$Want2See)
AllData$Con_Rev = factor(AllData$Con, levels = c('Coop','Comp'))
```


```{r Interaction-Behav}
if (redo_calc) {
  # Condition x Bet Interaction
  res = glmer(Choice ~ Cat_n_z + Con * Pred + (Con * Pred|Sub), AllData, 
              family = binomial(link="probit"), control = glmerControl(calc.derivs = FALSE))
  
  res2 = glmer(Choice ~ Cat_n + Con_Rev * Pred + (Con * Pred|Sub), AllData, 
              family = binomial(link="probit"), control = glmerControl(calc.derivs = FALSE))
  
  # Cooperation Condition: Does motivation bias participants' perceptual judgments?
  thisData = subset(AllData, Con == "Coop")
  res.coop = glmer(Choice ~ Cat_n_z + Pred + (Pred |Sub), thisData, family = binomial(link="probit"))
  
  # Competition Condition: Does motivation bias participants' perceptual judgments?
  thisData = subset(AllData, Con == "Comp")
  res.comp = glmer(Choice ~ Cat_n_z + Pred + (Pred |Sub), thisData, family = binomial(link="probit"))
  
  # Main Effect of Scene Proportion
  res.scene = glmer(Choice ~ Cat_n_z + (Cat_n_z|Sub), AllData, 
                    family = binomial(link="probit"), control = glmerControl(calc.derivs = FALSE));

  save(res,res2, res.coop, res.comp, res.scene, file="long_calc/ConditionxBet.Rda")

} else {
  load("long_calc/ConditionxBet.Rda")
}
```


```{r}
# Check for scene bias
scene_bias = AllData %>% filter(Cat_n == 50) %>%
  group_by(Sub) %>%
  summarise(avg_choice = mean(Choice ,na.rm =T))

t.test(x = scene_bias$avg_choice, mu = 0.5)
sem(scene_bias$avg_choice)
```

```{r plot-behav, fig.width = 5, fig.height = 3.5, warning=F}
thisData = AllData
thisData$Pred = recode(thisData$Pred,"0='Face';1='Scene'")

##  Run GLM (for visualization only, do not use for inference)
res.glm = glm(Choice ~ Cat_n, thisData, family = binomial(link="probit"))

# Create predicted dataset
pred.data = data.frame(Cat_n = rep(seq(0, 100, len = 101),4))
pred.data$Choice = predict.glm(res.glm,pred.data,type = "response")

# Compute Subject Average
sub_avg = group_by(thisData,Sub,Cat_n) %>% 
    summarise(Avg = mean(Choice, na.rm=T), SEM = sem(Choice))

# Plot group average with fit
ggplot() +
  stat_summary(data = sub_avg, aes(x=Cat_n,y=Avg),
               fun.y=mean,geom="point",size=2) +
  stat_summary(data = sub_avg, aes(x=Cat_n,y=Avg),
               fun.data = mean_cl_normal, geom = "errorbar",width=1,
               fun.args = list(mult = 1)) + 
  geom_line(data = pred.data, aes(x=Cat_n,y=Choice),size=1) +
  theme(legend.position="none",
      panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"),
        axis.text.x  = element_text(size=13,color="black"),
        axis.text.y  = element_text(size=13,color="black"),
        axis.title.x = element_text(size=15),
        axis.title.y = element_text(size=15),
        strip.background = element_blank(),
        strip.text.x = element_text(face = "bold", size = 15)) +
  xlab("% Scene") + ylab("P(Respond Scene)") 
```
 